apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-api
  name: product-api-service-pre
spec:
  ports:
  - name: http
    port: 8082
    nodePort: 31504
    targetPort: 8082
  selector:
    app: product-api-preproduction-pod
  type: NodePort